// <auto-generated />
namespace TableSource_CLE.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changeddisplaynamefordonationtype : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeddisplaynamefordonationtype));
        
        string IMigrationMetadata.Id
        {
            get { return "201611182230157_changed display name for donation type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
